# stats available at
# https://travis-ci.org/strukturag/libheif/
language: cpp
compiler:
  - gcc
  - clang
cache: ccache
sudo: required
env:
  - CHECK_LICENSES=1
  - WITH_LIBDE265= WITH_GRAPHICS=
  - WITH_LIBDE265= WITH_GRAPHICS=1
  - WITH_LIBDE265=1 WITH_GRAPHICS=1
  - WITH_LIBDE265=2 WITH_GRAPHICS=1
  - EMSCRIPTEN_VERSION=1.37.26
  - WITH_LIBDE265=1 WITH_GRAPHICS=1 TARBALL=1

matrix:
  exclude:
    - compiler: clang
      env: CHECK_LICENSES=1
    - compiler: clang
      env: EMSCRIPTEN_VERSION=1.37.26
    - compiler: clang
      env: WITH_LIBDE265=1 WITH_GRAPHICS=1 TARBALL=1

before_install:
  - ./scripts/install-ci.sh

before_script:
  - ./scripts/prepare-ci.sh

script:
  - ./scripts/run-ci.sh
