name: osx

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        runner: [ macos-13, macos-15 ]
        env:
          - { NAME: "nothing" }
          - { NAME: "cmake", WITH_GRAPHICS: 1, WITH_X265: 1, WITH_AOM: 1, WITH_LIBDE265: 1 }
          - { NAME: "libde265 (1) / x265 / graphics", WITH_GRAPHICS: 1, WITH_X265: 1, WITH_LIBDE265: 1 }
          - { NAME: "libde265 (2) / x265 / graphics", WITH_GRAPHICS: 1, WITH_X265: 1, WITH_LIBDE265: 2 }
    env: ${{ matrix.env }}
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v5

    - name: Install dependencies
      run: |
        ./scripts/install-ci-osx.sh

    - name: Prepare CI
      run: |
        ./scripts/prepare-ci.sh

    - name: Run tests
      run: |
        ./scripts/run-ci.sh
